config/routes.rb
Blogger2::Application.routes.draw do

  resources :tags

  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login' => "author_sessions#new"
  match 'logout' => "author_sessions#destroy"

  resources :articles do
    resources :comments
  end

  root to: "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image, :views
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x200#", thumb: "100x66>" }

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
    self.tags = new_or_found_tags
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author_name, :body
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, except: [:show, :index, :incPageView]
  
  def index
    @articles = Article.order("created_at DESC")
    @top3 = Article.order("views DESC").first(3)
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    incPageView(@article)
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    @article.views = 0
    @article.save

    flash.notice = "Successfully created '#{@article.title}'"
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])

    flash.notice = "'#{@article.title}'' updated"
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Successfully deleted '#{@article.title}'!"
    redirect_to articles_path
  end

  def incPageView(article)
    article.views += 1
    article.update_attributes(params[:views])
  end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:username], params[:password])
      redirect_back_or_to(articles_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, except: [:create]
  
  def create
    @comment = Comment.new(params[:comment])
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:destroy]
  
  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class="well well-small" style="padding-bottom:0px">
  <h4>Comment by <%= comment.author_name %></h4>
  <p><%= comment.body %></p>
  <p style="text-align:right"><small >Posted <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago</small></p>
</div>

app/views/articles/_edit_form.html.erb
<button type="button" data-toggle="modal" data-target="#myEdit" class="btn"><i class="icon-pencil"></i> Edit this Article?</button>

<div id="myEdit" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Edit Article</h3>
  </div>
  <div class="modal-body">
    <%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :style => "width:100%;" %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 6, :style => "width:100%;"  %>
  </p>
  <p>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, :style => "width:100%;" %>
  </p>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:medium), class: "img-polaroid"  %>
    <% end %>
    <%= f.label :image, "Attach an Image" %>
    <%= f.file_field :image, :style => "width:100%;" %>
  </p>
  </div>
  <div class="modal-footer">
      <p>
        <%= f.submit 'Submit', class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<button type="button" data-toggle="modal" data-target="#myModal" class="btn btn-primary pull-right">Create a new Article?</button>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">New Article</h3>
  </div>
  <div class="modal-body">
    <%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :style => "width:100%;" %>
  </p>
  <p>
    <%= f.label :body, "Main text, you may use HTML tags such as <p> and <strong> for formatting." %>
    <%= f.text_area :body, rows: 6, :style => "width:100%;" %>
  </p>
  <p>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, :style => "width:100%;" %>
  </p>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:medium), class: "img-polaroid"  %>
    <% end %>
    <%= f.label :image, "Attach an Image" %>
    <%= f.file_field :image, :style => "width:100%;" %>
  </p>
  </div>
  <div class="modal-footer">
      <p>
        <%= f.submit 'Submit', class: "btn btn-primary", :style => "width:100%;"  %>
      </p>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h2>Edit an Article</h2>

<%= render "form" %>

app/views/articles/index.html.erb
<h3>The Most Popular Articles</h3>
<div class="row">
  <div class="span12">
    <ul class="thumbnails">
      <% @top3.each do |article| %>
        <li class="span4">
          <div class="thumbnail">
            <p style="overflow:hidden; max-height:200px">
              <%= link_to image_tag(article.image.url(:medium), :style => "width:100%; border-radius:3px"), article_path(article) %>
            </p>
            <%= link_to article.title, article_path(article) %>
            <p>Viewed <%=  pluralize(article.views, 'time') %></p>
          </div>
        </li> 
      <% end %>
    </ul>
  </div>
</div>

<h3>Recent Articles</h3>

<div class="row">
  <div class="span12">
    <ul class="thumbnails">
      <% @articles.each do |article| %>
        <li class="span4">
          <div class="thumbnail">
            <p style="overflow:hidden; max-height:200px">
              <%= link_to image_tag(article.image.url(:medium), :style => "width:100%; border-radius:3px"), article_path(article) %>
            </p>
            <%= link_to article.title, article_path(article) %>
            <p>Viewed <%=  pluralize(article.views, 'time') %></p>
          </div>
        </li> 
      <% end %>
    </ul>
  </div>
</div>
<%= render partial: "layouts/nav_footer_index" %>

app/views/articles/new.html.erb
<h2>Create a New Article</h2>

<%= render "form" %>

app/views/articles/show.html.erb
<div class="row">
  <div class="span6 offset2">
    <h2><%= @article.title %></h2>
    <% if @article.image? %>
      <p><%= image_tag @article.image.url, class: "img-polaroid" %></p>
    <% end %>
    <p><%= raw(@article.body) %></p>
  </div>
  <div class="span2">
    <p class="well well-small">
      Tags:
      <% @article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
      <% end %>
    </p>
  </div>
</div>
<hr>

<div class="row">
  <div class="span2">
    <%= render partial: 'comments/form' %>
  </div>
  <div class="span6 well well-small", style="background:white; border:none; box-shadow:none">
    <p style="font-size:20px"><strong>Comments (<%= @article.comments.size %>)</strong></p>
    <%= render partial: 'articles/comment', collection: @article.comments %>
  </div>
</div>

<%= render partial: "layouts/nav_footer_show" %> 

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.username %></td>
    <td><%= author.email %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <b>Username:</b>
  <%= @author.username %>
</p>

<p>
  <b>Email:</b>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<button type="button" data-toggle="modal" data-target="#myModal" class="btn">Join the conversation?</button>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">New Comment</h3>
  </div>
  <div class="modal-body">
    <%= form_for [ @article, @comment ] do |f| %>
      <p>
        <%= f.label :author_name, "Your Name" %>
        <%= f.text_field :author_name %>
      </p>
      <p>
        <%= f.label :body, "Your Comment" %>
        <%= f.text_area :body, rows: 6, :style => "width:520px;" %>
      </p>
  </div>
  <div class="modal-footer">
      <p>
        <%= f.submit 'Submit', class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <%= link_to "Blog Title", root_path, class: "brand" %>
    <ul class="nav pull-right">
      <li><%= link_to "View by Tag", tags_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/_nav_footer_index.html.erb
<div class="navbar">
  <div class="navbar-inner">    
    <ul class="nav pull-right">  
      <% if logged_in? %>
        <li ><%= link_to "Logged in as #{current_user.username}, logout?", logout_path %></li>
        <li ><%= render partial: 'articles/form', class: "pull-right" %></li>
      <% else %>
        <li><%= link_to "Author? Login", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_nav_footer_show.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav pull-left">
      <li><%= link_to "Back to all Articles", articles_path %></li>
    </ul>
    <ul class="nav pull-right">  
      <% if logged_in? %>
        <li ><%= link_to "Logged in as #{current_user.username}, logout?", logout_path %></li>
        <li> <%= link_to "<i class='icon-trash'></i> Delete this article".html_safe, article_path, method: :delete, confirm: "Really delete the article?", class: "text-warning" %></li>
        <li ><%= render partial: 'articles/edit_form', class: "pull-right" %></li>

      <% else %>
        <li><%= link_to "Author? Login", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="flash">
    <%= flash.notice %>
  </p>
  <div class="container">
    <%= render partial: "layouts/nav" %>
    <div id="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul>
  <% @tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag) %></li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>